description: "Entropy Chatbot Evaluation"

prompts:
  - id: file://data/prompts/direct-v0.txt
    label: direct-v0

providers:
  - id: 'anthropic:messages:claude-sonnet-4-5-20250929'
    label: 'Claude Sonnet 4 (Web Search + Fetch)'
    prompts: [direct-v0]
    transform: file://transform.py
    config:
      max_tokens: 12000
      thinking:
        type: 'enabled'
        budget_tokens: 10000
      tools:
        - type: web_search_20250305
          name: web_search
          max_uses: 3
        - type: web_fetch_20250910
          name: web_fetch
          max_uses: 3

# Load test cases from CSV file
# CSV should have 'prompt' column for questions, other columns become metadata/context
tests: file://data/questions/30-real-questions.csv

defaultTest:
  assert:
    - type: llm-rubric
      provider: openai:gpt-4.1-mini
      value: 'Was the answer complete without any cutoffs? Mark as fail if the answer is truncated'


