description: "Entropy Chatbot Evaluation"

outputPath: public/evals/results.json

prompts:
  - id: file://public/prompts/direct-v0.txt
    label: direct-v0
  - id: file://public/prompts/clarify-web-v1.txt
    label: clarify-web-v1

providers:
  - id: 'anthropic:messages:claude-sonnet-4-5-20250929'
    label: 'Claude Sonnet 4 (Web Search + Fetch)'
    prompts: [direct-v0, clarify-web-v1]
    transform: file://transform.js
    config:
      max_tokens: 12000
      thinking:
        type: 'enabled'
        budget_tokens: 10000
      tools:
        - type: web_search_20250305
          name: web_search
          max_uses: 10
        - type: web_fetch_20250910
          name: web_fetch
          max_uses: 10

# Load test cases from CSV file
# CSV should have 'prompt' column for questions, other columns become metadata/context
tests: file://public/questions/30-real-questions.csv

defaultTest:
  assert:
    - type: llm-rubric
      provider: openai:gpt-4.1-mini
      value: 'Was the answer complete without any cutoffs? Mark as fail if the answer is truncated'


